version: 2

build:
  os: ubuntu-22.04

python:
  version: 3.12
  install:
    - pip install --upgrade pip setuptools
    - pip install "sphinx>=5.0"
    - pip install poetry poetry-plugin-export
    - poetry export -f requirements.txt -o req-docs.txt -E docs
    - pip install --no-cache-dir -r req-docs.txt
    - pip install --upgrade --no-cache-dir .

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

formats:
  - htmlzip
  - pdf
  - epub
