version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    # first, get pip & setuptools up to date
    - pip install --upgrade pip setuptools
    # force Sphinx >= 5.0 so sphinxcontrib.applehelp is happy
    - pip install "sphinx>=5.0"
    # install Poetry and export your docs extras
    - pip install poetry poetry-plugin-export
    - poetry export -f requirements.txt -o req-docs.txt -E docs
    # install your docs extras and your package itself
    - pip install --no-cache-dir -r req-docs.txt
    - pip install --upgrade --no-cache-dir .

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

formats:
  - htmlzip
  - pdf
  - epub
