version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    # 1) Upgrade pip & setuptools
    - pip install --upgrade pip setuptools

    # 2) Ensure Sphinx ≥ 5.0
    - pip install "sphinx>=5.0"

    # 3) Install Poetry and export your docs extras
    - pip install poetry poetry-plugin-export
    - poetry export -f requirements.txt -o req-docs.txt -E docs

    # 4) Install docs-extras and your package
    - pip install --no-cache-dir -r req-docs.txt
    - pip install --upgrade --no-cache-dir .

    # 5) Auto-generate API stubs
    - sphinx-apidoc --force --module-first --separate -o docs/source/api tuskitoo

    # 6) (Optional) Generate mermaid diagrams
    - python ./scripts/visualize-ga-workflow.py > docs/cicd_mermaid.md 2>/dev/null || echo "Skipping GA workflow visualization"
    - python ./scripts/visualize-dockerfile.py > docs/dockerfile_mermaid.md 2>/dev/null || echo "Skipping Dockerfile visualization"

    # 7) Build the HTML into RTD’s expected output directory
    - sphinx-build -b html docs/source $READTHEDOCS_OUTPUT/html

formats:
  - htmlzip
  - pdf
  - epub
